name: Netlify Clean-up Contexts

author: Snaplet

description: Delete environment variables in branch-deploy contexts

inputs:
  databaseEnvVar:
    description: Environment variables name associated with database connection string
    required: false
    type: string
    default: "DATABASE_URL"

runs:
  using: composite
  steps:
    - name: Delete
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/delete.mjs
